import { Heart, Zap, Eye, Crown } from 'lucide-react';
import { Category } from '../types';

export const emotionCategories: Category[] = [
  {
    id: 'confident_emotions',
    name: 'Selbstbewusste Emotionen',
    icon: 'Zap',
    section: 'emotion',
    subcategory: 'confident',
    options: [
      { id: 'confident', label: 'Selbstbewusst', value: 'confident expression', description: 'Ausstrahlende Sicherheit' },
      { id: 'proud', label: 'Stolz', value: 'proud demeanor', description: 'Stolze Haltung' },
      { id: 'dominant', label: 'Dominant', value: 'dominant presence', description: 'Dominante Ausstrahlung' },
      { id: 'authoritative', label: 'Autoritär', value: 'authoritative stance', description: 'Autoritäre Haltung' },
      { id: 'victorious', label: 'Siegreich', value: 'victorious expression', description: 'Siegreiche Ausstrahlung' },
      { id: 'triumphant', label: 'Triumphierend', value: 'triumphant pose', description: 'Triumphierende Pose' },
      { id: 'superior', label: 'Überlegen', value: 'superior attitude', description: 'Überlegene Haltung' },
      { id: 'powerful', label: 'Machtvoll', value: 'powerful presence', description: 'Machtvolle Präsenz' },
      { id: 'determined', label: 'Entschlossen', value: 'determined look', description: 'Entschlossener Blick' },
      { id: 'resolute', label: 'Bestimmt', value: 'resolute expression', description: 'Bestimmte Ausstrahlung' },
      { id: 'fearless', label: 'Furchtlos', value: 'fearless attitude', description: 'Furchtlose Haltung' },
      { id: 'brave', label: 'Mutig', value: 'brave stance', description: 'Mutige Haltung' },
      { id: 'bold', label: 'Kühn', value: 'bold expression', description: 'Kühne Ausstrahlung' },
      { id: 'fearless_warrior', label: 'Unerschrocken', value: 'fearless warrior spirit', description: 'Unerschrockener Kämpfergeist' },
      { id: 'rebellious', label: 'Rebellisch', value: 'rebellious attitude', description: 'Rebellische Haltung' },
      { id: 'provocative', label: 'Provokativ', value: 'provocative pose', description: 'Provokative Pose' },
      { id: 'challenging', label: 'Herausfordernd', value: 'challenging gaze', description: 'Herausfordernder Blick' },
      { id: 'cheeky', label: 'Frech', value: 'cheeky smile', description: 'Freches Lächeln' }
    ]
  },
  {
    id: 'mysterious_emotions',
    name: 'Geheimnisvolle Emotionen',
    icon: 'Eye',
    section: 'emotion',
    subcategory: 'mysterious',
    options: [
      { id: 'mysterious', label: 'Geheimnisvoll', value: 'mysterious expression', description: 'Geheimnisvolle Ausstrahlung' },
      { id: 'puzzling', label: 'Rätselhaft', value: 'puzzling demeanor', description: 'Rätselhafte Art' },
      { id: 'mystical', label: 'Mystisch', value: 'mystical aura', description: 'Mystische Aura' },
      { id: 'enigmatic', label: 'Enigmatisch', value: 'enigmatic smile', description: 'Enigmatisches Lächeln' },
      { id: 'inscrutable', label: 'Undurchschaubar', value: 'inscrutable expression', description: 'Undurchschaubarer Ausdruck' },
      { id: 'secretive', label: 'Verschwiegen', value: 'secretive look', description: 'Verschwiegener Blick' },
      { id: 'allusive', label: 'Andeutend', value: 'allusive gesture', description: 'Andeutende Geste' },
      { id: 'hidden', label: 'Versteckt', value: 'hidden meaning', description: 'Versteckte Bedeutung' },
      { id: 'cryptic', label: 'Hintergründig', value: 'cryptic smile', description: 'Hintergründiges Lächeln' },
      { id: 'ambiguous', label: 'Doppeldeutig', value: 'ambiguous expression', description: 'Doppeldeutiger Ausdruck' },
      { id: 'veiled', label: 'Verschleiert', value: 'veiled intentions', description: 'Verschleierte Absichten' },
      { id: 'subtle', label: 'Subtil', value: 'subtle hint', description: 'Subtiler Hinweis' },
      { id: 'dark_secret', label: 'Kryptisch', value: 'dark secrets', description: 'Dunkle Geheimnisse' },
      { id: 'concealed', label: 'Verborgen', value: 'concealed emotions', description: 'Verborgene Emotionen' },
      { id: 'multifaceted', label: 'Mehrdeutig', value: 'multifaceted personality', description: 'Vielschichtige Persönlichkeit' },
      { id: 'shadowy', label: 'Schattenhaft', value: 'shadowy presence', description: 'Schattenhafte Präsenz' },
      { id: 'dark', label: 'Dunkel', value: 'dark mystery', description: 'Dunkles Geheimnis' },
      { id: 'twilight', label: 'Zwielichtig', value: 'twilight mood', description: 'Zwielichtige Stimmung' }
    ]
  },
  {
    id: 'serene_emotions',
    name: 'Gelassene Emotionen',
    icon: 'Heart',
    section: 'emotion',
    subcategory: 'serene',
    options: [
      { id: 'serene', label: 'Gelassen', value: 'serene expression', description: 'Gelassene Ausstrahlung' },
      { id: 'calm', label: 'Ruhig', value: 'calm demeanor', description: 'Ruhige Art' },
      { id: 'relaxed', label: 'Entspannt', value: 'relaxed pose', description: 'Entspannte Haltung' },
      { id: 'peaceful', label: 'Friedlich', value: 'peaceful expression', description: 'Friedlicher Ausdruck' },
      { id: 'balanced', label: 'Ausgeglichen', value: 'balanced energy', description: 'Ausgeglichene Energie' },
      { id: 'harmonious', label: 'Harmonisch', value: 'harmonious presence', description: 'Harmonische Präsenz' },
      { id: 'composed', label: 'Besonnen', value: 'composed manner', description: 'Besonnene Art' },
      { id: 'meditative', label: 'Meditativ', value: 'meditative state', description: 'Meditativer Zustand' },
      { id: 'zen', label: 'Zen', value: 'zen-like calmness', description: 'Zen-artige Ruhe' },
      { id: 'stoic', label: 'Stoisch', value: 'stoic expression', description: 'Stoischer Ausdruck' },
      { id: 'unruffled', label: 'Gefasst', value: 'unruffled composure', description: 'Gefasste Haltung' },
      { id: 'unmoved', label: 'Ungerührt', value: 'unmoved by emotion', description: 'Ungerührt von Emotionen' },
      { id: 'equanimous', label: 'Gleichmütig', value: 'equanimous spirit', description: 'Gleichmütiger Geist' },
      { id: 'sovereign', label: 'Souverän', value: 'sovereign attitude', description: 'Souveräne Haltung' },
      { id: 'dignified', label: 'Würdevoll', value: 'dignified bearing', description: 'Würdevolle Haltung' },
      { id: 'majestic', label: 'Majestätisch', value: 'majestic presence', description: 'Majestätische Präsenz' },
      { id: 'sublime', label: 'Erhaben', value: 'sublime beauty', description: 'Erhabene Schönheit' },
      { id: 'noble', label: 'Noble', value: 'noble character', description: 'Nobler Charakter' }
    ]
  },
  {
    id: 'intense_emotions',
    name: 'Intensive Emotionen',
    icon: 'Zap',
    section: 'emotion',
    subcategory: 'intense',
    options: [
      { id: 'intense', label: 'Intensiv', value: 'intense gaze', description: 'Intensiver Blick' },
      { id: 'passionate', label: 'Leidenschaftlich', value: 'passionate expression', description: 'Leidenschaftlicher Ausdruck' },
      { id: 'burning', label: 'Brennend', value: 'burning desire', description: 'Brennende Leidenschaft' },
      { id: 'fiery', label: 'Feurig', value: 'fiery spirit', description: 'Feuriger Geist' },
      { id: 'glowing', label: 'Glühend', value: 'glowing passion', description: 'Glühende Leidenschaft' },
      { id: 'heated', label: 'Hitzig', value: 'heated emotion', description: 'Hitzige Emotion' },
      { id: 'explosive', label: 'Explosiv', value: 'explosive energy', description: 'Explosive Energie' },
      { id: 'dramatic', label: 'Dramatisch', value: 'dramatic intensity', description: 'Dramatische Intensität' },
      { id: 'electrifying', label: 'Elektrisierend', value: 'electrifying presence', description: 'Elektrisierende Präsenz' },
      { id: 'magnetic', label: 'Magnetisch', value: 'magnetic attraction', description: 'Magnetische Anziehung' },
      { id: 'hypnotic', label: 'Hypnotisch', value: 'hypnotic gaze', description: 'Hypnotischer Blick' },
      { id: 'enchanting', label: 'Bezaubernd', value: 'enchanting smile', description: 'Bezauberndes Lächeln' },
      { id: 'fascinating', label: 'Faszinierend', value: 'fascinating aura', description: 'Faszinierende Aura' },
      { id: 'intoxicating', label: 'Berauschend', value: 'intoxicating presence', description: 'Berauschende Präsenz' },
      { id: 'overwhelming', label: 'Überwältigend', value: 'overwhelming emotion', description: 'Überwältigende Emotion' },
      { id: 'breathtaking', label: 'Atemberaubend', value: 'breathtaking beauty', description: 'Atemberaubende Schönheit' },
      { id: 'stunning', label: 'Erschütternd', value: 'stunning impact', description: 'Erschütternde Wirkung' },
      { id: 'gripping', label: 'Ergreifend', value: 'gripping emotion', description: 'Ergreifende Emotion' }
    ]
  },
  {
    id: 'playful_emotions',
    name: 'Verspielte Emotionen',
    icon: 'Heart',
    section: 'emotion',
    subcategory: 'playful',
    options: [
      { id: 'playful', label: 'Verspielt', value: 'playful expression', description: 'Verspielte Ausstrahlung' },
      { id: 'mischievous', label: 'Schelmisch', value: 'mischievous grin', description: 'Schelmisches Grinsen' },
      { id: 'teasing', label: 'Neckisch', value: 'teasing smile', description: 'Neckendes Lächeln' },
      { id: 'coquettish', label: 'Kokett', value: 'coquettish pose', description: 'Kokette Pose' },
      { id: 'flirty', label: 'Flirtend', value: 'flirty glance', description: 'Flirtender Blick' },
      { id: 'charming', label: 'Charmant', value: 'charming smile', description: 'Charmantes Lächeln' },
      { id: 'bewitching', label: 'Bezaubernd', value: 'bewitching charm', description: 'Bezaubernder Charme' },
      { id: 'innocent', label: 'Unschuldig', value: 'innocent expression', description: 'Unschuldiger Ausdruck' },
      { id: 'naive', label: 'Naiv', value: 'naive charm', description: 'Naiver Charme' },
      { id: 'childlike', label: 'Kindlich', value: 'childlike wonder', description: 'Kindliches Staunen' },
      { id: 'lively', label: 'Lebhaft', value: 'lively spirit', description: 'Lebhafter Geist' },
      { id: 'quirky', label: 'Quirlig', value: 'quirky personality', description: 'Quirlige Persönlichkeit' },
      { id: 'bubbly', label: 'Spritzig', value: 'bubbly energy', description: 'Spritzige Energie' },
      { id: 'sassy', label: 'Frech', value: 'sassy attitude', description: 'Freche Haltung' },
      { id: 'pert', label: 'Keck', value: 'pert smile', description: 'Keckes Lächeln' },
      { id: 'clever', label: 'Pfiffig', value: 'clever expression', description: 'Pfiffiger Ausdruck' },
      { id: 'witty', label: 'Witzig', value: 'witty charm', description: 'Witziger Charme' },
      { id: 'humorous', label: 'Humorvoll', value: 'humorous spirit', description: 'Humorvoller Geist' }
    ]
  },
  {
    id: 'elegant_emotions',
    name: 'Elegante Emotionen',
    icon: 'Crown',
    section: 'emotion',
    subcategory: 'elegant',
    options: [
      { id: 'elegant', label: 'Elegant', value: 'elegant demeanor', description: 'Elegante Ausstrahlung' },
      { id: 'graceful', label: 'Anmutig', value: 'graceful movements', description: 'Anmutige Bewegungen' },
      { id: 'gracious', label: 'Graziös', value: 'gracious presence', description: 'Graziöse Präsenz' },
      { id: 'sophisticated', label: 'Sophisticated', value: 'sophisticated style', description: 'Sophistizierter Stil' },
      { id: 'cultured', label: 'Kultiviert', value: 'cultured refinement', description: 'Kultivierte Verfeinerung' },
      { id: 'refined', label: 'Raffiniert', value: 'refined elegance', description: 'Raffinierte Eleganz' },
      { id: 'tasteful', label: 'Geschmackvoll', value: 'tasteful presentation', description: 'Geschmackvolle Darstellung' },
      { id: 'stylish', label: 'Stilvoll', value: 'stylish appearance', description: 'Stilvolle Erscheinung' },
      { id: 'classic', label: 'Klassisch', value: 'classic beauty', description: 'Klassische Schönheit' },
      { id: 'timeless', label: 'Zeitlos', value: 'timeless elegance', description: 'Zeitlose Eleganz' },
      { id: 'noble', label: 'Edel', value: 'noble bearing', description: 'Edle Haltung' },
      { id: 'distinguished', label: 'Vornehm', value: 'distinguished manner', description: 'Vornehme Art' },
      { id: 'aristocratic', label: 'Distinguiert', value: 'aristocratic grace', description: 'Aristokratische Anmut' },
      { id: 'regal', label: 'Aristokratisch', value: 'regal bearing', description: 'Königliche Haltung' },
      { id: 'royal', label: 'Königlich', value: 'royal presence', description: 'Königliche Präsenz' },
      { id: 'princely', label: 'Fürstlich', value: 'princely demeanor', description: 'Fürstliche Ausstrahlung' },
      { id: 'sublime_elegant', label: 'Erhaben', value: 'sublime grace', description: 'Erhabene Anmut' },
      { id: 'luxurious', label: 'Luxuriös', value: 'luxurious appeal', description: 'Luxuriöse Ausstrahlung' }
    ]
  },
  {
    id: 'dreamy_emotions',
    name: 'Verträumte Emotionen',
    icon: 'Eye',
    section: 'emotion',
    subcategory: 'dreamy',
    options: [
      { id: 'dreamy', label: 'Verträumt', value: 'dreamy expression', description: 'Verträumter Ausdruck' },
      { id: 'romantic', label: 'Romantisch', value: 'romantic mood', description: 'Romantische Stimmung' },
      { id: 'swooning', label: 'Schwärmerisch', value: 'swooning expression', description: 'Schwärmerischer Ausdruck' },
      { id: 'longing', label: 'Sehnsüchtig', value: 'longing gaze', description: 'Sehnsüchtiger Blick' },
      { id: 'melancholic', label: 'Melancholisch', value: 'melancholic beauty', description: 'Melancholische Schönheit' },
      { id: 'wistful', label: 'Wehmütig', value: 'wistful smile', description: 'Wehmütiges Lächeln' },
      { id: 'nostalgic', label: 'Nostalgisch', value: 'nostalgic mood', description: 'Nostalgische Stimmung' },
      { id: 'sentimental', label: 'Sentimentál', value: 'sentimental expression', description: 'Sentimentaler Ausdruck' },
      { id: 'poetic', label: 'Poetisch', value: 'poetic beauty', description: 'Poetische Schönheit' },
      { id: 'artistic', label: 'Künstlerisch', value: 'artistic soul', description: 'Künstlerische Seele' },
      { id: 'inspired', label: 'Inspiriert', value: 'inspired creativity', description: 'Inspirierte Kreativität' },
      { id: 'visionary', label: 'Visionär', value: 'visionary look', description: 'Visionärer Blick' },
      { id: 'utopian', label: 'Utopisch', value: 'utopian dreams', description: 'Utopische Träume' },
      { id: 'idealistic', label: 'Idealistisch', value: 'idealistic spirit', description: 'Idealistischer Geist' },
      { id: 'hopeful', label: 'Hoffnungsvoll', value: 'hopeful expression', description: 'Hoffnungsvoller Ausdruck' },
      { id: 'wishing', label: 'Wünschend', value: 'wishing upon stars', description: 'Sterne herbeiwünschend' },
      { id: 'yearning', label: 'Sehnend', value: 'yearning heart', description: 'Sehnendes Herz' },
      { id: 'craving', label: 'Verlangend', value: 'craving desire', description: 'Verlangendes Begehren' }
    ]
  },
  {
    id: 'powerful_emotions',
    name: 'Kraftvolle Emotionen',
    icon: 'Zap',
    section: 'emotion',
    subcategory: 'powerful',
    options: [
      { id: 'powerful_emotion', label: 'Kraftvoll', value: 'powerful presence', description: 'Kraftvolle Präsenz' },
      { id: 'strong', label: 'Stark', value: 'strong character', description: 'Starker Charakter' },
      { id: 'mighty', label: 'Mächtig', value: 'mighty aura', description: 'Mächtige Aura' },
      { id: 'energetic', label: 'Energisch', value: 'energetic spirit', description: 'Energischer Geist' },
      { id: 'dynamic', label: 'Dynamisch', value: 'dynamic energy', description: 'Dynamische Energie' },
      { id: 'vital', label: 'Vital', value: 'vital force', description: 'Vitale Kraft' },
      { id: 'vibrant', label: 'Lebendig', value: 'vibrant energy', description: 'Lebendige Energie' },
      { id: 'pulsating', label: 'Pulsierend', value: 'pulsating life', description: 'Pulsierendes Leben' },
      { id: 'vibrating', label: 'Vibrierend', value: 'vibrating intensity', description: 'Vibrierende Intensität' },
      { id: 'electrifying_power', label: 'Elektrisierend', value: 'electrifying power', description: 'Elektrisierende Kraft' },
      { id: 'magical', label: 'Magisch', value: 'magical presence', description: 'Magische Präsenz' },
      { id: 'supernatural', label: 'Übernatürlich', value: 'supernatural power', description: 'Übernatürliche Kraft' },
      { id: 'divine', label: 'Göttlich', value: 'divine energy', description: 'Göttliche Energie' },
      { id: 'heroic', label: 'Heldenhaft', value: 'heroic spirit', description: 'Heldenhafter Geist' },
      { id: 'epic', label: 'Episch', value: 'epic grandeur', description: 'Epische Größe' },
      { id: 'monumental', label: 'Monumentál', value: 'monumental presence', description: 'Monumentale Präsenz' },
      { id: 'colossal', label: 'Gewaltig', value: 'colossal strength', description: 'Gewaltige Stärke' },
      { id: 'titanic', label: 'Titanisch', value: 'titanic power', description: 'Titanische Kraft' }
    ]
  }
];